
const $=s=>document.querySelector(s);
const starterBoards=[{id:1,title:"Schema jobb",color:"indigo",open:true,items:[{id:11,text:"Ändra Andreas schema",done:false},{id:12,text:"Ändra Elins schema",done:false},{id:13,text:"Kontrollera rasttider",done:true}]},{id:2,title:"Att förbereda",color:"amber",open:true,items:[{id:21,text:"Kopiera matematikuppgifter",done:false},{id:22,text:"Förbered material till NO",done:false}]}];
const colors={indigo:{border:"indigo-border",soft:"indigo-soft",stripe:"indigo-bg"},amber:{border:"amber-border",soft:"amber-soft",stripe:"amber-bg"},emerald:{border:"emerald-border",soft:"emerald-soft",stripe:"emerald-bg"},sky:{border:"sky-border",soft:"sky-soft",stripe:"sky-bg"},rose:{border:"rose-border",soft:"rose-soft",stripe:"rose-bg"}};
const load=(k,f)=>{try{const v=localStorage.getItem(k);return v?JSON.parse(v):f}catch{return f}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));let boards=load("new-dashboard-boards",starterBoards),activeBoardId=null,scheduleUrl="";
function esc(v){const e=document.createElement("div");e.textContent=String(v??"");return e.innerHTML}
function clock(){const n=new Date();$("#weekday").textContent=new Intl.DateTimeFormat("sv-SE",{weekday:"long"}).format(n);$("#dateText").textContent=new Intl.DateTimeFormat("sv-SE",{day:"numeric",month:"long",year:"numeric"}).format(n);$("#timeText").textContent=new Intl.DateTimeFormat("sv-SE",{hour:"2-digit",minute:"2-digit"}).format(n);$("#secondsText").textContent=new Intl.DateTimeFormat("sv-SE",{second:"2-digit"}).format(n)}
function db(){return new Promise((ok,no)=>{const r=indexedDB.open("new-larardashboard-db",1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains("images"))r.result.createObjectStore("images")};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function putImage(blob){const d=await db();return new Promise((ok,no)=>{const t=d.transaction("images","readwrite");t.objectStore("images").put(blob,"schedule");t.oncomplete=()=>{d.close();ok()};t.onerror=()=>{d.close();no(t.error)}})}
async function getImage(){const d=await db();return new Promise((ok,no)=>{const t=d.transaction("images","readonly"),r=t.objectStore("images").get("schedule");r.onsuccess=()=>{d.close();ok(r.result||null)};r.onerror=()=>{d.close();no(r.error)}})}
async function delImage(){const d=await db();return new Promise((ok,no)=>{const t=d.transaction("images","readwrite");t.objectStore("images").delete("schedule");t.oncomplete=()=>{d.close();ok()};t.onerror=()=>{d.close();no(t.error)}})}
async function compress(file){if(!file||!file.type.startsWith("image/"))throw Error("Välj en bildfil");const url=URL.createObjectURL(file);try{const img=await new Promise((ok,no)=>{const i=new Image;i.onload=()=>ok(i);i.onerror=()=>no(Error("Bilden kunde inte läsas"));i.src=url});const scale=Math.min(1,1800/img.naturalWidth,1400/img.naturalHeight),w=Math.max(1,Math.round(img.naturalWidth*scale)),h=Math.max(1,Math.round(img.naturalHeight*scale)),c=document.createElement("canvas");c.width=w;c.height=h;const x=c.getContext("2d",{alpha:false});x.fillStyle="#fff";x.fillRect(0,0,w,h);x.drawImage(img,0,0,w,h);return await new Promise((ok,no)=>c.toBlob(b=>b?ok(b):no(Error("Komprimeringen misslyckades")),"image/jpeg",.82))}finally{URL.revokeObjectURL(url)}}
function showImage(blob){if(scheduleUrl)URL.revokeObjectURL(scheduleUrl);scheduleUrl=blob?URL.createObjectURL(blob):"";$("#scheduleEmpty").classList.toggle("hidden",!!blob);$("#schedulePreview").classList.toggle("hidden",!blob);$("#uploadText").textContent=blob?"Byt bild":"Ladda upp";if(blob)$("#scheduleImage").src=scheduleUrl}
async function selectImage(file){try{const blob=await compress(file);await putImage(blob);showImage(blob)}catch(e){alert("Bilden kunde inte sparas: "+e.message)}}
function render(){const total=boards.reduce((s,b)=>s+b.items.length,0),done=boards.reduce((s,b)=>s+b.items.filter(i=>i.done).length,0);$("#progressText").textContent=`${done} av ${total} punkter färdiga`;if(!boards.length){$("#boardList").innerHTML='<button class="empty-boards" data-new-board><span>＋</span><b>Skapa ditt första anteckningsblock</b></button>';return}$("#boardList").innerHTML=boards.map(b=>{const c=colors[b.color]||colors.indigo,d=b.items.filter(i=>i.done).length,items=b.items.length?b.items.map(i=>`<div class="item-row"><button class="check-button ${i.done?"done":""}" data-toggle-item="${b.id}:${i.id}">${i.done?"✓":""}</button><span class="item-text ${i.done?"done":""}">${esc(i.text)}</span><button class="delete-button" data-delete-item="${b.id}:${i.id}">×</button></div>`).join(""):`<button class="empty-items" data-add-item="${b.id}">＋ Lägg till första punkten</button>`;return `<article class="board-card ${c.border}"><span class="board-stripe ${c.stripe}"></span><div class="board-top"><button class="board-toggle" data-toggle-board="${b.id}"><span class="chevron ${c.soft}">${b.open?"⌄":"›"}</span><span class="board-name"><strong>${esc(b.title)}</strong><small>${d} av ${b.items.length} färdiga</small></span></button><button class="icon-button" data-add-item="${b.id}" title="Lägg till punkt">＋</button><button class="icon-button" data-delete-board="${b.id}" title="Ta bort block">⋯</button></div>${b.open?`<div class="board-items">${items}</div>`:""}</article>`}).join("")}
function openDialog(id){$("#"+id).showModal()}function closeDialog(id){$("#"+id).close()}
[$("#scheduleFile"),$("#scheduleFileEmpty")].forEach(input=>input.addEventListener("change",async e=>{await selectImage(e.target.files?.[0]);e.target.value=""}));
$("#removeSchedule").onclick=async()=>{await delImage();showImage(null)};$("#newBoardButton").onclick=()=>openDialog("boardDialog");
document.addEventListener("click",e=>{const t=e.target.closest("[data-toggle-board]");if(t){boards=boards.map(b=>String(b.id)===t.dataset.toggleBoard?{...b,open:!b.open}:b);save("new-dashboard-boards",boards);render()}const a=e.target.closest("[data-add-item]");if(a){activeBoardId=Number(a.dataset.addItem);openDialog("itemDialog")}const ti=e.target.closest("[data-toggle-item]");if(ti){const [bid,iid]=ti.dataset.toggleItem.split(":").map(Number);boards=boards.map(b=>b.id===bid?{...b,items:b.items.map(i=>i.id===iid?{...i,done:!i.done}:i)}:b);save("new-dashboard-boards",boards);render()}const di=e.target.closest("[data-delete-item]");if(di){const [bid,iid]=di.dataset.deleteItem.split(":").map(Number);boards=boards.map(b=>b.id===bid?{...b,items:b.items.filter(i=>i.id!==iid)}:b);save("new-dashboard-boards",boards);render()}const db=e.target.closest("[data-delete-board]");if(db&&confirm("Ta bort anteckningsblocket?")){boards=boards.filter(b=>String(b.id)!==db.dataset.deleteBoard);save("new-dashboard-boards",boards);render()}if(e.target.closest("[data-new-board]"))openDialog("boardDialog");const c=e.target.closest("[data-close]");if(c)closeDialog(c.dataset.close)});
$("#boardForm").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),title=String(f.get("title")||"").trim();if(!title)return;boards.push({id:Date.now(),title,color:String(f.get("color")||"indigo"),open:true,items:[]});save("new-dashboard-boards",boards);e.target.reset();e.target.querySelector('[value="indigo"]').checked=true;closeDialog("boardDialog");render()};
$("#itemForm").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),text=String(f.get("text")||"").trim();if(!text)return;boards=boards.map(b=>b.id===activeBoardId?{...b,open:true,items:[...b.items,{id:Date.now(),text,done:false}]}:b);save("new-dashboard-boards",boards);e.target.reset();closeDialog("itemDialog");render()};
if("serviceWorker" in navigator)addEventListener("load",()=>navigator.serviceWorker.register("sw.js").then(r=>r.update()).catch(console.error));clock();setInterval(clock,1000);getImage().then(showImage).catch(()=>showImage(null));render();
